version: "3.9"
services:
  expense-manager-app:
    build:
      dockerfile: hosting/app/Dockerfile
    network_mode: host
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      PORT: 3000
  postgresql:
    build: hosting/database/postresql
    network_mode: host
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: expense_manager
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
  postgresql-adminer:
    depends_on:
      - postgresql
    build: hosting/database/adminer
    network_mode: host
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: expense_manager
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root

volumes:
  postgresql-volume:
  pgadmin-volume:
